version: "3.9"

services:
  plex:
    image: linuxserver/plex:arm64v8-1.26.0
    container_name: plex
    network_mode: host
    devices:
      - /dev/bus/usb/:/dev/bus/usb/
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM_ID}
    volumes:
      - ~/plex/library:/config
      - ~/plex/tvshow:/tv
      - ~/plex/movies:/movies
    restart: unless-stopped



    