version: "3.9"

services:
  plex:
    image: linuxserver/plex:arm64v8-1.26.0
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-6jx7a4jNAHQb_vf6Q8gH
    volumes:
      - /home/levankhelo/plex/library:/config
      - /home/levankhelo/plex/tvshow:/tv
      - /home/levankhelo/plex/movies:/movies
    restart: unless-stopped



    